[package]
name          = "tcp-stream"
version       = "0.20.9" # remember to update html_root_url
authors       = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition       = "2018"
description   = "mio's TcpStream on steroids"
repository    = "https://github.com/Keruspe/tcp-stream"
documentation = "https://docs.rs/tcp-stream"
keywords      = ["tcp", "mio", "io", "async", "non-blocking"]
categories    = ["asynchronous", "network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "tcp_stream"

[features]
default                   = ["native-tls"]
dangerous-configuration   = ["rustls-connector/dangerous-configuration"]
native-tls                = ["native-tls-crate", "pem"]
quic                      = ["rustls-connector/quic"]
rustls                    = ["rustls-native-certs"]
rustls-webpki-roots-certs = ["rustls-common", "rustls-connector/webpki-roots-certs"]
rustls-native-certs       = ["rustls-common", "rustls-connector/native-certs"]
rustls-common             = ["rustls-connector", "p12"]
vendored-openssl          = ["openssl/vendored"]

[dependencies]
cfg-if = "^1.0"

[dependencies.mio]
version  = "^0.7.6"
default-features = false
features = ["net", "os-poll"]

[dependencies.native-tls-crate]
package  = "native-tls"
version  = "^0.2"
optional = true

[dependencies.openssl]
version  = "^0.10"
optional = true

[dependencies.p12]
version = "^0.4"
optional = true

[dependencies.pem]
version = "^0.8"
optional = true

[dependencies.rustls-connector]
version          = "^0.13"
optional         = true
default-features = false

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "Keruspe/tcp-stream" }
appveyor  = { repository = "Keruspe/tcp-stream" }
